import React, { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import axios from "axios";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function MaintenanceReport() {
    const query = new URLSearchParams(useLocation().search);
    const vehicleId = query.get("id");
    const navigate = useNavigate();

    const [vehicle, setVehicle] = useState(null);
    const [records, setRecords] = useState([]);
    const [totalCost, setTotalCost] = useState(0);

    // ✅ Fetch Vehicle + Maintenance Data
    useEffect(() => {
        const fetchAll = async () => {
            try {
                const vehicleRes = await axios.get("/api/vehicles");
                const vehicleData = vehicleRes.data.vehicles.find((v) => v._id === vehicleId);
                setVehicle(vehicleData);

                const recordRes = await axios.get(`/api/maintenance/${vehicleId}`);
                setRecords(recordRes.data.records || []);

                const total = recordRes.data.records.reduce(
                    (sum, rec) => sum + (Number(rec.totalCost) || 0),
                    0
                );
                setTotalCost(total);
            } catch (err) {
                console.error("❌ Error fetching report data:", err);
            }
        };
        fetchAll();
    }, [vehicleId]);

// ✅ Generate PDF Report (Fixed Fonts + Layout)
const handleDownload = () => {
  try {
    const doc = new jsPDF("p", "mm", "a4");

    // Use only ASCII characters to avoid font issues
    const formatRupee = (val) => `Rs. ${val || 0}`;

    // 🔹 Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(30, 30, 30);
    doc.text("Heavy Vehicle Management System", 14, 18);

    doc.setFontSize(13);
    doc.text("Vehicle Maintenance Report", 14, 28);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 36);

    // 🔹 Vehicle Info
    let startY = 48;
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    if (vehicle) {
      const info = [
        `Vehicle Name: ${vehicle.name || "N/A"}`,
        `Model: ${vehicle.vehicleModel || "N/A"}`,
        `Registration Number: ${vehicle.registrationNumber || "N/A"}`,
        `Fuel Type: ${vehicle.fuelType || "N/A"}`,
        `Vehicle Type: ${vehicle.vehicleType || "N/A"}`,
        `Manufacturing Year: ${vehicle.manufacturingYear || "N/A"}`
      ];
      info.forEach((line, i) => doc.text(line, 14, startY + i * 7));
    }

    // 🔹 Maintenance Table
    const tableData = records.map((r, i) => [
      i + 1,
      r.serviceType || "—",
      r.replacedParts || "—",
      formatRupee(r.totalCost),
      r.serviceDate?.split("T")[0] || "—",
      r.startDate?.split("T")[0] || "—",
      r.endDate?.split("T")[0] || "—",
    ]);

    autoTable(doc, {
      startY: 95,
      head: [["#", "Service Type", "Replaced Parts", "Cost", "Service Date", "Start", "End"]],
      body: tableData,
      theme: "grid",
      headStyles: { fillColor: [40, 89, 215], textColor: 255 },
      styles: { font: "helvetica", fontSize: 10, cellPadding: 2 },
    });

    // 🔹 Total Summary
    const finalY = doc.lastAutoTable.finalY + 10;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(`Total Maintenance Cost: ${formatRupee(totalCost)}`, 14, finalY);

    // 🔹 Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(
      "Generated by Heavy Vehicle Management System | © 2025 HVMS",
      14,
      pageHeight - 10
    );

    // Save
    const filename = `${vehicle?.name || "Vehicle"}_Maintenance_Report.pdf`;
    doc.save(filename);
  } catch (err) {
    console.error("PDF Generation Error:", err);
    alert("⚠️ Failed to generate report. Please check console.");
  }
};

    if (!vehicle)
        return <div className="p-8 text-gray-500 text-center">Loading report data...</div>;

    // ✅ UI
    return (
        <div className="max-w-6xl mx-auto p-8 bg-white rounded-xl shadow-lg mt-6 mb-12">
            {/* Header */}
            <div className="flex justify-between items-center mb-8">
                <div>
                    <h1 className="text-3xl font-bold text-gray-800">
                        📋 Vehicle Maintenance Report
                    </h1>
                    <p className="text-gray-500">
                        Generated by Heavy Vehicle Management System
                    </p>
                </div>
                <button
                    onClick={handleDownload}
                    className="bg-blue-700 text-white px-5 py-2 rounded-lg hover:bg-blue-800"
                >
                    ⬇️ Download Report
                </button>
            </div>

            {/* Vehicle Info */}
            <section className="bg-gray-50 border p-6 rounded-xl mb-8">
                <h2 className="text-xl font-semibold text-gray-700 mb-4">🚘 Vehicle Information</h2>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm text-gray-700">
                    <p><strong>Name:</strong> {vehicle.name}</p>
                    <p><strong>Model:</strong> {vehicle.vehicleModel}</p>
                    <p><strong>Registration:</strong> {vehicle.registrationNumber}</p>
                    <p><strong>Fuel Type:</strong> {vehicle.fuelType}</p>
                    <p><strong>Type:</strong> {vehicle.vehicleType}</p>
                    <p><strong>Manufacturing Year:</strong> {vehicle.manufacturingYear}</p>
                </div>
            </section>

            {/* Maintenance History */}
            <section>
                <h2 className="text-xl font-semibold text-gray-700 mb-4">🔧 Maintenance History</h2>
                {records.length === 0 ? (
                    <p className="text-gray-500 italic">No maintenance records available.</p>
                ) : (
                    <div className="overflow-x-auto">
                        <table className="min-w-full border border-gray-200 text-sm">
                            <thead className="bg-gray-100 text-gray-700">
                                <tr>
                                    <th className="p-3 border">S.No</th>
                                    <th className="p-3 border">Service Type</th>
                                    <th className="p-3 border">Replaced Parts</th>
                                    <th className="p-3 border">Cost (₹)</th>
                                    <th className="p-3 border">Service Date</th>
                                    <th className="p-3 border">Start Date</th>
                                    <th className="p-3 border">End Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                {records.map((r, i) => (
                                    <tr key={r._id} className="border-t hover:bg-gray-50">
                                        <td className="p-3 border text-center">{i + 1}</td>
                                        <td className="p-3 border">{r.serviceType || "—"}</td>
                                        <td className="p-3 border">{r.replacedParts || "—"}</td>
                                        <td className="p-3 border text-right">₹{r.totalCost || 0}</td>
                                        <td className="p-3 border">{r.serviceDate?.split("T")[0] || "—"}</td>
                                        <td className="p-3 border">{r.startDate?.split("T")[0] || "—"}</td>
                                        <td className="p-3 border">{r.endDate?.split("T")[0] || "—"}</td>
                                    </tr>
                                ))}
                                <tr className="bg-gray-50 font-semibold text-gray-800">
                                    <td className="p-3 border text-right" colSpan={3}>
                                        Total Maintenance Cost
                                    </td>
                                    <td className="p-3 border text-right">₹{totalCost}</td>
                                    <td colSpan={3}></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                )}
            </section>

            <div className="mt-8 flex justify-end">
                <button
                    onClick={() => navigate(-1)}
                    className="border px-5 py-2 rounded-lg hover:bg-gray-100"
                >
                    ← Back
                </button>
            </div>
        </div>
    );
}
